### ISSUE TITLE
Lucien Suggestion

### ISSUE THREAD

**Issue by Aosana** [Lost-Outpost/dragonborn#1]
[Lucien - Immersive Fully Voiced Male Follower](https://www.nexusmods.com/skyrimspecialedition/mods/20035) would be a great inclusion to this list! He just recently got support for voice lines in [Beyond Skyrim - Bruma](https://www.nexusmods.com/skyrimspecialedition/mods/10917), and he has a dozen or so patches for Creation Club mods that further expand his dialogue options. He's among the most well-made and polished follower mods on the Nexus, and I'd love to have him adventuring here in Dragonborn as well!

**Comment by Aosana** [comment]
Also I can't add my own labels this SUCKS

**Comment by Guitarninja2** [comment]
Put it into the 1.1.0 roadmap
https://github.com/Lost-Outpost/dragonborn/issues/5
