### ISSUE TITLE
Savior's Hide ctd on female characters

### ISSUE THREAD

**Issue by Lakuar** [Lost-Outpost/dragonborn#11]
Wearing the Savior's Hide armor on female player characters crashes the game.
Steps to reproduce:
1. get savior's hide through console or quest
2. equip savior's hide
3. change gender to female with racemenu--> ctd
Alternatively:
1. change gender to female with racemenu
2. equip savior's hide
3. save game and load save --> ctd

**Comment by Guitarninja2** [comment]
Fixed for 1.0.19
