### ISSUE TITLE
Weird Textures in Ice Dungeon in Bruma (v1.0.11)

### ISSUE THREAD

**Issue by m0thde** [Lost-Outpost/dragonborn#12]
They look like static on TV screen (it moves). Dungeon is Frostfire Cave, Cold's Embrace. 
 
![20230103062521_1](https://user-images.githubusercontent.com/121763260/210417236-d4a84bbf-4865-4013-9e80-9f5c41919b71.jpg)

**Comment by Guitarninja2** [comment]
Fixed in 1.1.0
