### ISSUE TITLE
ELFX Overrides Ruins Clutter Improved Spider Clutter (1.0.25)

### ISSUE THREAD

**Issue by Dwailing** [Lost-Outpost/dragonborn#18]
Ruins Clutter Improved includes the following meshes:

meshes\effects\fxspiderwebkitdinnerhuman.nif
meshes\effects\fxspiderwebkitdinnerhumangnd.nif
meshes\effects\fxspiderwebkitskeeverdinner.nif
meshes\effects\fxspiderwebkitskeeverdinnerstatictemp.nif

which are overridden by ELFX. This results in significantly lower quality versions of these models taking priority. I would recommend hiding or removing the ELFX meshes to allow RCI's meshes to show in game as they are much easier on the eyes and I believe do not result in any major issues with ELFX.

**Comment by Guitarninja2** [comment]
Done
