### ISSUE TITLE
Good News and Bad News regarding the dual cast magnitude bug

### ISSUE THREAD

**Issue by IIBendyII** [Lost-Outpost/dragonborn#2]
My test method was to start a new game, console command the calm spell book, teleport to dragonsreach, toggle god mode and start dual cast spamming the calm spell on balgruuf, farengar, ireleth and commander caius (at least i think that was his name). They are all level 10 npcs, meaning they can only be calmed with the basic calm spell by dual casting it.

Good News: I know what mod is causing the dual cast magnitude bug, it's "dTry's Key Utils". Having the esp active, makes the dual cast fail almost 100% of the time if you move your character. If you are standing still there is no issue, but if you dual cast while moving the dual cast magnitude fails. Disabling the esp fixed the problem.

Bad News: I know for experience it's not the only mod that can cause dual casting do fail. From reading comments in other discords, having survival mode active, depending on your load order can cause the bug to happen, although in my testing it only happened once in what felt like a hundred attempts.
Also, on the Septimus modlist, I did several tests disabling different mods including both "dTry's Key Utils" and Survival Mode, and the bug still happened most of the time. Defeated by my limited knowledge, at the time I just concluded that it was a combination of different mods and script overload that made it happen and abbandoned my illusionist playthrough :(

However, in the small modlist that is Dragonborn, disabling "dTry's Key Utils" fixed the problem completely with survival mode disabled. With it enabled, it happened only once in 10 minutes of non stop dual casting the calm spell on the dragonsreach npcs (I like survival and such a slim chance i find it acceptable).
I still do not know what other mods are causing this problem in the Semptimus modlist...

**Comment by alexgadam** [comment]
To add to this - I think the dual cast bug is not just limited to illusion spells

A good test is the following:
- Add a flesh spell
- Add the (Adamant) alteration perk barrier
- Dual cast the spell on yourself
- Look at the duration and check if it has been correctly tripled (according to the barrier perk). 

This might be useful for future testing as you don't need to teleport to a place with actors and cast on them - you can do it in isolation in the starting cell.

I found in Septimus this would fail ~50% of the time to apply the barrier perk. On Dragonborn it fails far less often. 

Just so I understand - in your testing, what happens if you only use Survival Mode, but disable Survival Mode Improved?

**Comment by IIBendyII** [comment]
Yeah, I know that the dual cast bug is not limited to just Illusion spells, I didn't thought about the barrier perk as a testing method.

I found that casting calm spells on high level NPCs was the most effective way to detect it, since it is a chance based bug, and I can dual cast calm hundreds of times in a few minutes to more or less guess the faliure percentage.

About survival mode, I didn't try to disable the Improved .esp, i simply deactivated the mod from the settings/gameplay menu ingame. But even after having it reactivated, the bug happened only once in over 10 minutes of repetedly casting calm, and it could also have been me failing to click both the right and left mouse buttons at the same time to dual cast (Doing the same thing over and over kind of put me in a bot like state of mind...). So... I don't know. If i feel like testing some more I'll report my results.

**Comment by IIBendyII** [comment]
I did some more testing with version 1.0.10 of this modlist. I have not experienced the dual cast bug with or without survival mode active. Tested with both the casting calm method and the barrier method suggested for over 15 minutes.
