### ISSUE TITLE
SMIM textures loading after Skyland (1.0.27)

### ISSUE THREAD

**Issue by Dwailing** [Lost-Outpost/dragonborn#21]
Right now the way the plugin load order is configured has SMIM loading its archive after Skyland's archives, causing the Skyland SMIM texture replacements (and some vanilla textures that overlap between the two) to not load. Moving the SMIM plugin before the Skyland plugins should fix this, but this may have unintended side effects re: record conflicts and other archive priorities.

**Comment by Guitarninja2** [comment]
Fixed in the next update
