### ISSUE TITLE
Base Object Swapper needs updated from 2.5.0 to 2.5.1 (1.0.27)

### ISSUE THREAD

**Issue by Dwailing** [Lost-Outpost/dragonborn#22]
The version of BOS used in the list currently (2.5.0) has a bug which makes it unable to properly process swapping forms on a per-cell basis. This bug is fixed in version 2.5.1. It doesn't directly impact any of the mods used in the list currently, but it requires manual updating when adding mods to the list on the user side and may impact the addition of other mods to the list at a later time.

**Comment by Guitarninja2** [comment]
Fixed in the next update
