### ISSUE TITLE
Assorted Mods with Available Updates (1.1.10)

### ISSUE THREAD

**Issue by Dwailing** [Lost-Outpost/dragonborn#29]
This is just a quick compilation of mods in the list that I've verified have updates available currently:

[Mod Name - installed version => available version]
[Crash Logger](https://www.nexusmods.com/skyrimspecialedition/mods/59818?) - 1.1.0 => 1.7.0
[Keyword Item Distributor](https://www.nexusmods.com/skyrimspecialedition/mods/55728) - 2.1.1 => 2.2.0
[QUI](https://www.nexusmods.com/skyrimspecialedition/mods/65343) - 0.3.1.1 => 0.3.2
[FormList Manipulator](https://www.nexusmods.com/skyrimspecialedition/mods/74037) - 1.5.3 => 1.5.4
[Unofficial Skyrim Special Edition Patch](https://www.nexusmods.com/skyrimspecialedition/mods/266) - 4.2.7 => 4.2.8
[Particle Patch for ENB](https://www.nexusmods.com/skyrimspecialedition/mods/65720) - 1.1.7 => 1.2.2
[Cathedral 3D Mountain Flowers](https://www.nexusmods.com/skyrimspecialedition/mods/41312) - 2.0 => 2.1 (Hearthfire Patch in Update Files)
[ELFX Shadows](https://www.nexusmods.com/skyrimspecialedition/mods/63790) - 1.2 => 1.4
[Chapter II](https://www.nexusmods.com/skyrimspecialedition/mods/37792) - 3.0 => 3.1
[Forceful Tongue Audio Overhaul for Skyrim Patch](https://www.nexusmods.com/skyrimspecialedition/mods/36276) - 1.0.1 => 1.0.2
[CC Staves Mysticism Compatibility Patch](https://www.nexusmods.com/skyrimspecialedition/mods/78659) - 1.2 => 1.4
[Extended Cut Saints and Seducers](https://www.nexusmods.com/skyrimspecialedition/mods/72772) - 1.0.0.3 => 1.0.0.4
[NPCs Wear Amulets of Mara](https://www.nexusmods.com/skyrimspecialedition/mods/66125) - 2.01 => 2.02
[New Armory Series Elven Steel Weapons](https://www.nexusmods.com/skyrimspecialedition/mods/78888) - 1.00 => 1.01 (possibly not necessary as update fixes leveled list issue which may have been removed for modlist)
[Bandit Spellswords](https://www.nexusmods.com/skyrimspecialedition/mods/81791) - 1.1 => 1.2

**Comment by Guitarninja2** [comment]
All done. Thank you for the help!
