### ISSUE TITLE
Vanilla HDR ini Settings Missing (1.1.10)

### ISSUE THREAD

**Issue by Dwailing** [Lost-Outpost/dragonborn#30]
From the page for Vanilla HDR:

"
This must be in SkyrimPrefs.ini
[General]
fLightingOutputColourClampPostEnv = 9999.0000
fLightingOutputColourClampPostLit = 9999.0000
fLightingOutputColourClampPostSpec = 9999.0000

Recommended, add to SkyrimCustom.ini
[Display]
bIBLFEnable=1
uIBLFBlurRadiusX = 9.0000
uIBLFBlurRadiusY = 9.0000
fIBLFLightsRangeDownshift = 0.0000
fIBLFGlobalIntensity = 0.3000
"

Neither of these settings tweaks are present in Dragonborn's ini files, and adding them noticeably changes the game's visuals. I think without them Vanilla HDR has no substantive effect on the game's visuals. I would recommend either adding a note to the mod that they need to be added to the inis if you want to use Vanilla HDR, or creating a dummy esp and matching ini to ensure that they're added appropriately when Vanilla HDR is used.

**Comment by Guitarninja2** [comment]
Decided to remove this from the base list
