### ISSUE TITLE
no way to get the sword of Jyggallag from Saints and Seducers

### ISSUE THREAD

**Issue by thehermittt** [Lost-Outpost/dragonborn#34]
when you kill Thoron the final boss of the mod he does not drop the sword of jyggallag, though he fights you with it, and there is no way to get that sword from what i saw

**Comment by m0thde** [comment]
I had a similar issue, so I added it via console. It was unenchanted and lackluster. Is the player _supposed_ to be able to obtain it?

**Comment by Mykomark** [comment]
> I had a similar issue, so I added it via console. It was unenchanted and lackluster. Is the player _supposed_ to be able to obtain it?

Yea that sword is from CC and as I remember he's unenchanted.

**Comment by thehermittt** [comment]
yes it's supposed to be unenchanted, i just like how it looks and wanted to use it for my enchanter playthrough. in the original cc you get it at the end, so i thought it should be the case here as well?
