### ISSUE TITLE
Patch is needed for SEC: S&S and Apothecary Food

### ISSUE THREAD

**Issue by m0thde** [Lost-Outpost/dragonborn#39]
Foods in Skyrim Extended Cut: Saints & Seducers do not follow Apothecary Food rules.
![20230204065328_1](https://user-images.githubusercontent.com/121763260/216798381-8081dc65-96b1-4bb2-b371-c63e5190af80.jpg)
Seems like a patch is available here: https://www.nexusmods.com/skyrimspecialedition/mods/74508

**Comment by Guitarninja2** [comment]
Done for 1.2.2
