### ISSUE TITLE
1.08 Texture Issue when not using ENB Complex Grass

### ISSUE THREAD

**Issue by 4ulender** [Lost-Outpost/dragonborn#4]
Noticed this texture issue after loading up 1.08. I skipped playing a few updates, this issue was not present in 1.05.
![20221222103545_1](https://user-images.githubusercontent.com/96638017/209169763-8111941d-2529-4363-80e6-a50425bd5798.jpg)

For performance reasons I was not planning on using any ENB so I disabled all of the mods under ENB options. The texture issue goes away if I re-enable the two ENB Complex Grass mods and the ENB Binaries. This could have just been user error on my part - I had assumed that if not using ENB, then I should disable all the mods in that section. If I had to guess, maybe mods enabled when the latest Terrain LODs were generated and so it caused issues when I disabled them?

![image](https://user-images.githubusercontent.com/96638017/209173058-c390bb56-fe91-4014-a6b5-fcc3abe922f9.png)

**Comment by Guitarninja2** [comment]
Fixed in 1.0.9
