### ISSUE TITLE
Mod Updates (critical ones as well)

### ISSUE THREAD

**Issue by D1Z4STR** [Lost-Outpost/dragonborn#42]
Combing the list and there are mod updates that are in hand. Please update the manifest at your earliest convenience.

- [x] 1. 1.3.2 uses older 5.4.0 of Po3's papyrus extender and not 5.5.0 (7Feb23)
- [x] 2. 1.3.2 uses older 6.30 and not 6.4.0 of SPID (31Jan23)
- [x] 3. 1.3.2 uses older 1.7.5 and not 1.8.0 of Po3's Tweaks (17Feb23)
- [x] 4. 1.3.2 uses older 1.5.0 (21Sep22) and not current 1.5.0 Improvement Names Customized AE (28Dec22)
- [x] 5. 1.3.2 uses old deleted file from Nexus (marked deleted) 1.2 for CritterSpawn Congestion Fix. The current is v 1.3 (14Jan23)
- [x] 6. 1.3.2 uses older 0.77 and not 0.78 for Assorted Mesh Fixes (29Jan23)
- [x] 7. 1.3.2 uses older Alpha-29 of Dyndolod resources, latest is Alpha-31
- [x] 8. 1.3.2 uses older 0.6 of Animated Forge Water, latest is 0.7 (9Feb23)
- [x] 9. 1.3.2 uses Simplicity of Snow - Real 3d walls but the mod has been taken down or moved (??)
- [x] 10. 1.3.2 uses older 2.9.0 of Atherius, the newest is 2.10.3 (3Feb23)
- [x] 11. 1.3.2 uses older 1.8.2 of Mundus, the newest is 1.9.1 (30Jan23)
- [x] 12. 1.3.2 for some odd reason is not grabbing the latest Hand to Hand - Adamant addon 1.4.3 (10Feb23) I checked the archives and I am not seeing what main file it downloads lol
- [x] 13. 1.3.2 uses older 2.1.0 of Blade and Blunt, the newest is 2.1.1 (10Feb23)
- [x] 14. 1.3.2 uses older 1.60 of Skyrim's Got Talent, the newest is 1.61 (12Jan23)
- [x] 15. 1.3.2 uses older 1.2 of Ancient Knowledge - Automation Summoning, the newest is 1.3 (15Jan23)
- [x] 16. 1.3.2 uses older 1.0 of Saints and Seducers - Mysticism Rebalance, the newest is 1.8 for both the main and optional file (13Jan23)

I stopped at the end of Balance Tweaks so far....

**Comment by D1Z4STR** [comment]
-Continuing on the band wagon-

17. 1.3.2 uses older 1.11 of College of Winterhold - Quest Expansion, the newest is 1.12 (12Jan23)
18. 1.3.2 uses older 1.0 of Innocence Lost - Quest Expansion, the newest is 1.01 (17Jan23)
19. 1.3.2 uses older 9.0.1 More to Say, the newest is 9.0.2 (13Feb23)
20. Serana Dialogue Edit I am not sure what exact file it is downloading... Nexus does not show a download date for any file on the mod page ??? - double check
21. Finding Velehk Sain I am not sure what exact file it is downloading... Nexus does not show a download date for any file on the mod page ??? - double check
22. Beyond Skyrim Bruma uses Creation Club Goblins I am not sure what exact file it is downloading... Nexus does not show a download date for any file on the mod page ??? - double check
23. 1.3.2 uses older 1.0.1 of Ancient Nord Armo(u)ry Lite, newest is 1.0.2 (5Feb23) - might also want optional CC fishing patch?

**Comment by Guitarninja2** [comment]
Finished. Will get this released today.

**Comment by D1Z4STR** [comment]
Thanks GN!
