### ISSUE TITLE
CTD on Launch

### ISSUE THREAD

**Issue by JessiahC** [Lost-Outpost/dragonborn#43]
Using Wabbajack install.

Getting a CTD on first launch of the game through MO2.  The game crashes right when the image of Bleak Falls Barrow appears after shaders are done. 

Completely fresh installs of Wabbajack, Skyrim SE, and Dragonborn. Located on F: drive, 64gb ram / 40gb pagefile, all prereqs installed.  Game does launch and run from skse64_loader.  Tried running apps as administrator with no change.

Looking for any suggestions before I try disabling mods one by one. On discord: Jes#3186

[crash-2023-02-19-07-13-06.log](https://github.com/Lost-Outpost/dragonborn/files/10776341/crash-2023-02-19-07-13-06.log)

**Comment by Guitarninja2** [comment]
You need to install the creation club content. Read the install guide..

**Comment by JessiahC** [comment]
Sorry for wasting your time, I read that header as 'If you have anniversary' and skipped it, totally my fault.
