### ISSUE TITLE
Snow LOD

### ISSUE THREAD

**Issue by LoD7995** [Lost-Outpost/dragonborn#45]
Snow LOD seems to be to dark in general. Simplicity of Snow sadly doesn't incorporate any adjustments to snow LOD. 
Before:
![Mountains Before](https://user-images.githubusercontent.com/83468628/219970458-8eab65b6-8107-4677-b2b9-7a7e92596431.png)
After:
![Mountains After](https://user-images.githubusercontent.com/83468628/219970478-99a3b8f7-23ca-4295-bff7-bfd708d21b4a.png)
Before:
![Map Before](https://user-images.githubusercontent.com/83468628/219970471-8b7987c6-51ee-4935-b2fd-1b5290afe50b.png)
After:
![Map After](https://user-images.githubusercontent.com/83468628/219970462-bf23dded-237b-4ec4-b35e-bcfef84ff811.png)

Small file to remedy this (see screenshots above):
[SnowLODFix.zip](https://github.com/Lost-Outpost/dragonborn/files/10777734/SnowLODFix.zip)

**Comment by LoD7995** [comment]
I basically changed the snow colour to pure white (255,255,255).

**Comment by Guitarninja2** [comment]
Thank you yeah. I missed this fix when I added Simplicity of Snow back
