### ISSUE TITLE
Texture inconsistency beach/sand

### ISSUE THREAD

**Issue by Kornil** [Lost-Outpost/dragonborn#53]
![IMG_20230221_233137.jpg](https://user-images.githubusercontent.com/11630180/220474141-37ec51e8-74b0-4b15-8a5a-56453d9ed6bd.jpg)

Islands north of winterhold the new beach textures do not fully replace/integrate the rocky beach textures

**Comment by Guitarninja2** [comment]
This should be fixed in 1.4.0
