### ISSUE TITLE
I can't run

### ISSUE THREAD

**Issue by GeorgeSamourgkanidis** [Lost-Outpost/dragonborn#58]
I updated the modlist after 1-2 months but for some reason I can't run. When I ride the horse I can run normally, but on foot it doesn't do anything. Any idea?

**Comment by GeorgeSamourgkanidis** [comment]
Looks like my stamina won't regenerate. I used a stamina potions and I can run normally. Health regenerates correctly.

**Comment by D1Z4STR** [comment]
is your character overweight?

**Comment by GeorgeSamourgkanidis** [comment]
> is your character overweight?

No
