### ISSUE TITLE
Horse/Stable Vendors Sell Lockpicks

### ISSUE THREAD

**Issue by m0thde** [Lost-Outpost/dragonborn#59]
Horse/Stable vendors can sell lockpicks. This is inconsistent with the mod Merchant - A Trading Expansion. I believe Press H to Horse is responsible for adding Horse/Stable vendors. _A very tiny issue._
*Edit: Birna in Winterhold also sells lockpicks. I'll keep an eye out for other vendors.

**Comment by Guitarninja2** [comment]
Lockpicks are still sold. Just less often.
