### ISSUE TITLE
Huntsman & Dragonbroth Stew Foods Not Categorized Correctly for COCKS Menu

### ISSUE THREAD

**Issue by m0thde** [Lost-Outpost/dragonborn#60]
- [ ] Huntsman foods are all in the "Other" category despite some foods having category words in their names.
- [ ] Dragonbroth stew is in "Misc" category with an ingot icon.
![20230227142021_1](https://user-images.githubusercontent.com/121763260/221737973-be31a55a-d5d9-4f4b-b7e8-45a3d80b70b6.jpg)
![20230227142017_1](https://user-images.githubusercontent.com/121763260/221737998-f78815c1-78dd-43a5-bb57-63aaffd2febd.jpg)

**Comment by Guitarninja2** [comment]
Should be now
