### ISSUE TITLE
Buggy Waterfall Effect

### ISSUE THREAD

**Issue by AlexiosDesius** [Lost-Outpost/dragonborn#65]
Strange issue occurring with small waterfalls in Dimfrost in Wyrmstooth. Occurs with ReShade enabled and disabled.

![20230613165128_1](https://github.com/Lost-Outpost/dragonborn/assets/136516097/7d86c55e-53c8-47bb-9466-8e89a95ed50b)

**Comment by AlexiosDesius** [comment]
A similar issue occurs with the wave effect on Blackbone Isle (The Dead Man's Dread Creation).

![20230617135148_1](https://github.com/Lost-Outpost/dragonborn/assets/136516097/a7ceda22-8f96-4f01-9dd3-5319bbc8caaf)

**Comment by jaaimino** [comment]
This is fixed in 1.0.23
